apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}
  labels:
    {{- include "node-ipam-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-manager-role
  labels:
    {{- include "node-ipam-controller.labels" . | nindent 4 }}
rules:
  {{- (.Files.Get "gen/role.yaml" | fromYaml).rules | toYaml | nindent 0}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-rolebinding
  labels:
    {{- include "node-ipam-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "node-ipam-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-manager-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create","get","list"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["update"]
  resourceNames: ["node-ipam-controller"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-ipam-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-manager-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}